// Code generated by protoc-gen-go. DO NOT EDIT.
// source: fastfabric/remote/storage.proto

package remote

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	common "github.com/hyperledger/fabric/protos/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StorageRequest struct {
	LedgerId             string        `protobuf:"bytes,1,opt,name=ledgerId,proto3" json:"ledgerId,omitempty"`
	Block                *common.Block `protobuf:"bytes,2,opt,name=block,proto3" json:"block,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *StorageRequest) Reset()         { *m = StorageRequest{} }
func (m *StorageRequest) String() string { return proto.CompactTextString(m) }
func (*StorageRequest) ProtoMessage()    {}
func (*StorageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d58cfc72f8c0700, []int{0}
}

func (m *StorageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StorageRequest.Unmarshal(m, b)
}
func (m *StorageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StorageRequest.Marshal(b, m, deterministic)
}
func (m *StorageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorageRequest.Merge(m, src)
}
func (m *StorageRequest) XXX_Size() int {
	return xxx_messageInfo_StorageRequest.Size(m)
}
func (m *StorageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StorageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StorageRequest proto.InternalMessageInfo

func (m *StorageRequest) GetLedgerId() string {
	if m != nil {
		return m.LedgerId
	}
	return ""
}

func (m *StorageRequest) GetBlock() *common.Block {
	if m != nil {
		return m.Block
	}
	return nil
}

type Result struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d58cfc72f8c0700, []int{1}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

type GetBlockchainInfoRequest struct {
	LedgerId             string   `protobuf:"bytes,1,opt,name=ledgerId,proto3" json:"ledgerId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBlockchainInfoRequest) Reset()         { *m = GetBlockchainInfoRequest{} }
func (m *GetBlockchainInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetBlockchainInfoRequest) ProtoMessage()    {}
func (*GetBlockchainInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d58cfc72f8c0700, []int{2}
}

func (m *GetBlockchainInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockchainInfoRequest.Unmarshal(m, b)
}
func (m *GetBlockchainInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockchainInfoRequest.Marshal(b, m, deterministic)
}
func (m *GetBlockchainInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockchainInfoRequest.Merge(m, src)
}
func (m *GetBlockchainInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetBlockchainInfoRequest.Size(m)
}
func (m *GetBlockchainInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockchainInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockchainInfoRequest proto.InternalMessageInfo

func (m *GetBlockchainInfoRequest) GetLedgerId() string {
	if m != nil {
		return m.LedgerId
	}
	return ""
}

type RetrieveBlockByHashRequest struct {
	LedgerId             string   `protobuf:"bytes,1,opt,name=ledgerId,proto3" json:"ledgerId,omitempty"`
	BlockHash            []byte   `protobuf:"bytes,2,opt,name=blockHash,proto3" json:"blockHash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RetrieveBlockByHashRequest) Reset()         { *m = RetrieveBlockByHashRequest{} }
func (m *RetrieveBlockByHashRequest) String() string { return proto.CompactTextString(m) }
func (*RetrieveBlockByHashRequest) ProtoMessage()    {}
func (*RetrieveBlockByHashRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d58cfc72f8c0700, []int{3}
}

func (m *RetrieveBlockByHashRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetrieveBlockByHashRequest.Unmarshal(m, b)
}
func (m *RetrieveBlockByHashRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetrieveBlockByHashRequest.Marshal(b, m, deterministic)
}
func (m *RetrieveBlockByHashRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetrieveBlockByHashRequest.Merge(m, src)
}
func (m *RetrieveBlockByHashRequest) XXX_Size() int {
	return xxx_messageInfo_RetrieveBlockByHashRequest.Size(m)
}
func (m *RetrieveBlockByHashRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RetrieveBlockByHashRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RetrieveBlockByHashRequest proto.InternalMessageInfo

func (m *RetrieveBlockByHashRequest) GetLedgerId() string {
	if m != nil {
		return m.LedgerId
	}
	return ""
}

func (m *RetrieveBlockByHashRequest) GetBlockHash() []byte {
	if m != nil {
		return m.BlockHash
	}
	return nil
}

type RetrieveBlockByNumberRequest struct {
	LedgerId             string   `protobuf:"bytes,1,opt,name=ledgerId,proto3" json:"ledgerId,omitempty"`
	BlockNo              uint64   `protobuf:"varint,2,opt,name=blockNo,proto3" json:"blockNo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RetrieveBlockByNumberRequest) Reset()         { *m = RetrieveBlockByNumberRequest{} }
func (m *RetrieveBlockByNumberRequest) String() string { return proto.CompactTextString(m) }
func (*RetrieveBlockByNumberRequest) ProtoMessage()    {}
func (*RetrieveBlockByNumberRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d58cfc72f8c0700, []int{4}
}

func (m *RetrieveBlockByNumberRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetrieveBlockByNumberRequest.Unmarshal(m, b)
}
func (m *RetrieveBlockByNumberRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetrieveBlockByNumberRequest.Marshal(b, m, deterministic)
}
func (m *RetrieveBlockByNumberRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetrieveBlockByNumberRequest.Merge(m, src)
}
func (m *RetrieveBlockByNumberRequest) XXX_Size() int {
	return xxx_messageInfo_RetrieveBlockByNumberRequest.Size(m)
}
func (m *RetrieveBlockByNumberRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RetrieveBlockByNumberRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RetrieveBlockByNumberRequest proto.InternalMessageInfo

func (m *RetrieveBlockByNumberRequest) GetLedgerId() string {
	if m != nil {
		return m.LedgerId
	}
	return ""
}

func (m *RetrieveBlockByNumberRequest) GetBlockNo() uint64 {
	if m != nil {
		return m.BlockNo
	}
	return 0
}

type RetrieveTxByIDRequest struct {
	LedgerId             string   `protobuf:"bytes,1,opt,name=ledgerId,proto3" json:"ledgerId,omitempty"`
	TxID                 string   `protobuf:"bytes,2,opt,name=txID,proto3" json:"txID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RetrieveTxByIDRequest) Reset()         { *m = RetrieveTxByIDRequest{} }
func (m *RetrieveTxByIDRequest) String() string { return proto.CompactTextString(m) }
func (*RetrieveTxByIDRequest) ProtoMessage()    {}
func (*RetrieveTxByIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d58cfc72f8c0700, []int{5}
}

func (m *RetrieveTxByIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetrieveTxByIDRequest.Unmarshal(m, b)
}
func (m *RetrieveTxByIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetrieveTxByIDRequest.Marshal(b, m, deterministic)
}
func (m *RetrieveTxByIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetrieveTxByIDRequest.Merge(m, src)
}
func (m *RetrieveTxByIDRequest) XXX_Size() int {
	return xxx_messageInfo_RetrieveTxByIDRequest.Size(m)
}
func (m *RetrieveTxByIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RetrieveTxByIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RetrieveTxByIDRequest proto.InternalMessageInfo

func (m *RetrieveTxByIDRequest) GetLedgerId() string {
	if m != nil {
		return m.LedgerId
	}
	return ""
}

func (m *RetrieveTxByIDRequest) GetTxID() string {
	if m != nil {
		return m.TxID
	}
	return ""
}

type RetrieveTxByBlockNumTranNumRequest struct {
	LedgerId             string   `protobuf:"bytes,1,opt,name=ledgerId,proto3" json:"ledgerId,omitempty"`
	BlockNo              uint64   `protobuf:"varint,2,opt,name=blockNo,proto3" json:"blockNo,omitempty"`
	TxNo                 uint64   `protobuf:"varint,3,opt,name=txNo,proto3" json:"txNo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RetrieveTxByBlockNumTranNumRequest) Reset()         { *m = RetrieveTxByBlockNumTranNumRequest{} }
func (m *RetrieveTxByBlockNumTranNumRequest) String() string { return proto.CompactTextString(m) }
func (*RetrieveTxByBlockNumTranNumRequest) ProtoMessage()    {}
func (*RetrieveTxByBlockNumTranNumRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d58cfc72f8c0700, []int{6}
}

func (m *RetrieveTxByBlockNumTranNumRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetrieveTxByBlockNumTranNumRequest.Unmarshal(m, b)
}
func (m *RetrieveTxByBlockNumTranNumRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetrieveTxByBlockNumTranNumRequest.Marshal(b, m, deterministic)
}
func (m *RetrieveTxByBlockNumTranNumRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetrieveTxByBlockNumTranNumRequest.Merge(m, src)
}
func (m *RetrieveTxByBlockNumTranNumRequest) XXX_Size() int {
	return xxx_messageInfo_RetrieveTxByBlockNumTranNumRequest.Size(m)
}
func (m *RetrieveTxByBlockNumTranNumRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RetrieveTxByBlockNumTranNumRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RetrieveTxByBlockNumTranNumRequest proto.InternalMessageInfo

func (m *RetrieveTxByBlockNumTranNumRequest) GetLedgerId() string {
	if m != nil {
		return m.LedgerId
	}
	return ""
}

func (m *RetrieveTxByBlockNumTranNumRequest) GetBlockNo() uint64 {
	if m != nil {
		return m.BlockNo
	}
	return 0
}

func (m *RetrieveTxByBlockNumTranNumRequest) GetTxNo() uint64 {
	if m != nil {
		return m.TxNo
	}
	return 0
}

type RetrieveBlockByTxIDRequest struct {
	LedgerId             string   `protobuf:"bytes,1,opt,name=ledgerId,proto3" json:"ledgerId,omitempty"`
	TxID                 string   `protobuf:"bytes,2,opt,name=txID,proto3" json:"txID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RetrieveBlockByTxIDRequest) Reset()         { *m = RetrieveBlockByTxIDRequest{} }
func (m *RetrieveBlockByTxIDRequest) String() string { return proto.CompactTextString(m) }
func (*RetrieveBlockByTxIDRequest) ProtoMessage()    {}
func (*RetrieveBlockByTxIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d58cfc72f8c0700, []int{7}
}

func (m *RetrieveBlockByTxIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetrieveBlockByTxIDRequest.Unmarshal(m, b)
}
func (m *RetrieveBlockByTxIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetrieveBlockByTxIDRequest.Marshal(b, m, deterministic)
}
func (m *RetrieveBlockByTxIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetrieveBlockByTxIDRequest.Merge(m, src)
}
func (m *RetrieveBlockByTxIDRequest) XXX_Size() int {
	return xxx_messageInfo_RetrieveBlockByTxIDRequest.Size(m)
}
func (m *RetrieveBlockByTxIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RetrieveBlockByTxIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RetrieveBlockByTxIDRequest proto.InternalMessageInfo

func (m *RetrieveBlockByTxIDRequest) GetLedgerId() string {
	if m != nil {
		return m.LedgerId
	}
	return ""
}

func (m *RetrieveBlockByTxIDRequest) GetTxID() string {
	if m != nil {
		return m.TxID
	}
	return ""
}

type RetrieveTxValidationCodeByTxIDRequest struct {
	LedgerId             string   `protobuf:"bytes,1,opt,name=ledgerId,proto3" json:"ledgerId,omitempty"`
	TxID                 string   `protobuf:"bytes,2,opt,name=txID,proto3" json:"txID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RetrieveTxValidationCodeByTxIDRequest) Reset()         { *m = RetrieveTxValidationCodeByTxIDRequest{} }
func (m *RetrieveTxValidationCodeByTxIDRequest) String() string { return proto.CompactTextString(m) }
func (*RetrieveTxValidationCodeByTxIDRequest) ProtoMessage()    {}
func (*RetrieveTxValidationCodeByTxIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d58cfc72f8c0700, []int{8}
}

func (m *RetrieveTxValidationCodeByTxIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetrieveTxValidationCodeByTxIDRequest.Unmarshal(m, b)
}
func (m *RetrieveTxValidationCodeByTxIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetrieveTxValidationCodeByTxIDRequest.Marshal(b, m, deterministic)
}
func (m *RetrieveTxValidationCodeByTxIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetrieveTxValidationCodeByTxIDRequest.Merge(m, src)
}
func (m *RetrieveTxValidationCodeByTxIDRequest) XXX_Size() int {
	return xxx_messageInfo_RetrieveTxValidationCodeByTxIDRequest.Size(m)
}
func (m *RetrieveTxValidationCodeByTxIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RetrieveTxValidationCodeByTxIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RetrieveTxValidationCodeByTxIDRequest proto.InternalMessageInfo

func (m *RetrieveTxValidationCodeByTxIDRequest) GetLedgerId() string {
	if m != nil {
		return m.LedgerId
	}
	return ""
}

func (m *RetrieveTxValidationCodeByTxIDRequest) GetTxID() string {
	if m != nil {
		return m.TxID
	}
	return ""
}

type ValidationCode struct {
	ValidationCode       int32    `protobuf:"varint,1,opt,name=validationCode,proto3" json:"validationCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidationCode) Reset()         { *m = ValidationCode{} }
func (m *ValidationCode) String() string { return proto.CompactTextString(m) }
func (*ValidationCode) ProtoMessage()    {}
func (*ValidationCode) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d58cfc72f8c0700, []int{9}
}

func (m *ValidationCode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidationCode.Unmarshal(m, b)
}
func (m *ValidationCode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidationCode.Marshal(b, m, deterministic)
}
func (m *ValidationCode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidationCode.Merge(m, src)
}
func (m *ValidationCode) XXX_Size() int {
	return xxx_messageInfo_ValidationCode.Size(m)
}
func (m *ValidationCode) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidationCode.DiscardUnknown(m)
}

var xxx_messageInfo_ValidationCode proto.InternalMessageInfo

func (m *ValidationCode) GetValidationCode() int32 {
	if m != nil {
		return m.ValidationCode
	}
	return 0
}

type RetrieveBlocksRequest struct {
	LedgerId             string   `protobuf:"bytes,1,opt,name=ledgerId,proto3" json:"ledgerId,omitempty"`
	StartNum             uint64   `protobuf:"varint,2,opt,name=startNum,proto3" json:"startNum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RetrieveBlocksRequest) Reset()         { *m = RetrieveBlocksRequest{} }
func (m *RetrieveBlocksRequest) String() string { return proto.CompactTextString(m) }
func (*RetrieveBlocksRequest) ProtoMessage()    {}
func (*RetrieveBlocksRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d58cfc72f8c0700, []int{10}
}

func (m *RetrieveBlocksRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetrieveBlocksRequest.Unmarshal(m, b)
}
func (m *RetrieveBlocksRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetrieveBlocksRequest.Marshal(b, m, deterministic)
}
func (m *RetrieveBlocksRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetrieveBlocksRequest.Merge(m, src)
}
func (m *RetrieveBlocksRequest) XXX_Size() int {
	return xxx_messageInfo_RetrieveBlocksRequest.Size(m)
}
func (m *RetrieveBlocksRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RetrieveBlocksRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RetrieveBlocksRequest proto.InternalMessageInfo

func (m *RetrieveBlocksRequest) GetLedgerId() string {
	if m != nil {
		return m.LedgerId
	}
	return ""
}

func (m *RetrieveBlocksRequest) GetStartNum() uint64 {
	if m != nil {
		return m.StartNum
	}
	return 0
}

type Iterator struct {
	IteratorId           int32    `protobuf:"varint,1,opt,name=iteratorId,proto3" json:"iteratorId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Iterator) Reset()         { *m = Iterator{} }
func (m *Iterator) String() string { return proto.CompactTextString(m) }
func (*Iterator) ProtoMessage()    {}
func (*Iterator) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d58cfc72f8c0700, []int{11}
}

func (m *Iterator) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Iterator.Unmarshal(m, b)
}
func (m *Iterator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Iterator.Marshal(b, m, deterministic)
}
func (m *Iterator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Iterator.Merge(m, src)
}
func (m *Iterator) XXX_Size() int {
	return xxx_messageInfo_Iterator.Size(m)
}
func (m *Iterator) XXX_DiscardUnknown() {
	xxx_messageInfo_Iterator.DiscardUnknown(m)
}

var xxx_messageInfo_Iterator proto.InternalMessageInfo

func (m *Iterator) GetIteratorId() int32 {
	if m != nil {
		return m.IteratorId
	}
	return 0
}

func init() {
	proto.RegisterType((*StorageRequest)(nil), "remote.StorageRequest")
	proto.RegisterType((*Result)(nil), "remote.Result")
	proto.RegisterType((*GetBlockchainInfoRequest)(nil), "remote.GetBlockchainInfoRequest")
	proto.RegisterType((*RetrieveBlockByHashRequest)(nil), "remote.RetrieveBlockByHashRequest")
	proto.RegisterType((*RetrieveBlockByNumberRequest)(nil), "remote.RetrieveBlockByNumberRequest")
	proto.RegisterType((*RetrieveTxByIDRequest)(nil), "remote.RetrieveTxByIDRequest")
	proto.RegisterType((*RetrieveTxByBlockNumTranNumRequest)(nil), "remote.RetrieveTxByBlockNumTranNumRequest")
	proto.RegisterType((*RetrieveBlockByTxIDRequest)(nil), "remote.RetrieveBlockByTxIDRequest")
	proto.RegisterType((*RetrieveTxValidationCodeByTxIDRequest)(nil), "remote.RetrieveTxValidationCodeByTxIDRequest")
	proto.RegisterType((*ValidationCode)(nil), "remote.ValidationCode")
	proto.RegisterType((*RetrieveBlocksRequest)(nil), "remote.RetrieveBlocksRequest")
	proto.RegisterType((*Iterator)(nil), "remote.Iterator")
}

func init() { proto.RegisterFile("fastfabric/remote/storage.proto", fileDescriptor_5d58cfc72f8c0700) }

var fileDescriptor_5d58cfc72f8c0700 = []byte{
	// 555 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x95, 0xdd, 0x6f, 0x12, 0x4d,
	0x14, 0xc6, 0xe1, 0x7d, 0x0b, 0xc2, 0x69, 0x4b, 0xea, 0x18, 0x1b, 0x32, 0xd6, 0x4a, 0xc6, 0x8f,
	0x34, 0x4d, 0x84, 0xd8, 0x26, 0xc6, 0x6b, 0xa8, 0xa9, 0x18, 0xb3, 0xd5, 0x91, 0xd4, 0x2b, 0x2f,
	0x06, 0x38, 0xb4, 0x1b, 0x77, 0x77, 0xea, 0xec, 0x2c, 0xa1, 0xb7, 0xfe, 0xe5, 0x86, 0xd9, 0x1d,
	0x60, 0x58, 0x20, 0xc4, 0x5e, 0xb1, 0xe7, 0x63, 0x7f, 0xf3, 0xcc, 0xe1, 0x3c, 0x00, 0x2f, 0x46,
	0x22, 0xd6, 0x23, 0xd1, 0x57, 0xfe, 0xa0, 0xa5, 0x30, 0x94, 0x1a, 0x5b, 0xb1, 0x96, 0x4a, 0xdc,
	0x60, 0xf3, 0x4e, 0x49, 0x2d, 0x49, 0x39, 0xcd, 0x52, 0x6a, 0xc2, 0xb8, 0x35, 0x90, 0x61, 0x28,
	0xa3, 0xec, 0x23, 0xed, 0x59, 0xae, 0x05, 0x38, 0xbc, 0x41, 0x95, 0xd6, 0xd8, 0x37, 0xa8, 0x7d,
	0x4f, 0x81, 0x1c, 0x7f, 0x27, 0x18, 0x6b, 0x42, 0xa1, 0x92, 0x76, 0x74, 0x87, 0xf5, 0x62, 0xa3,
	0x78, 0x52, 0xe5, 0xb3, 0x98, 0xbc, 0x84, 0x52, 0x3f, 0x90, 0x83, 0x5f, 0xf5, 0xff, 0x1a, 0xc5,
	0x93, 0xdd, 0xb3, 0xfd, 0x66, 0x76, 0x4e, 0x7b, 0x9a, 0xe4, 0x69, 0x8d, 0x55, 0xa0, 0xcc, 0x31,
	0x4e, 0x02, 0xcd, 0xde, 0x43, 0xfd, 0x12, 0xb5, 0x29, 0x0e, 0x6e, 0x85, 0x1f, 0x75, 0xa3, 0x91,
	0xdc, 0xe2, 0x18, 0x76, 0x0d, 0x94, 0xa3, 0x56, 0x3e, 0x8e, 0xd1, 0xbc, 0xdc, 0xbe, 0xff, 0x24,
	0xe2, 0xdb, 0x6d, 0x04, 0x1e, 0x41, 0xd5, 0x88, 0x98, 0xf6, 0x1b, 0x91, 0x7b, 0x7c, 0x9e, 0x60,
	0x3d, 0x38, 0x5a, 0xe2, 0x7a, 0x49, 0xd8, 0x47, 0xb5, 0x0d, 0xb9, 0x0e, 0x8f, 0x0c, 0xc8, 0x93,
	0x86, 0xbb, 0xc3, 0x6d, 0xc8, 0x2e, 0xe1, 0xa9, 0xa5, 0xf6, 0x26, 0xed, 0xfb, 0xee, 0xc5, 0x36,
	0x38, 0x02, 0x3b, 0x7a, 0xd2, 0xbd, 0x30, 0xac, 0x2a, 0x37, 0xcf, 0x2c, 0x02, 0xb6, 0x08, 0x32,
	0x12, 0xbd, 0x24, 0xec, 0x29, 0x11, 0x79, 0x49, 0xf8, 0x20, 0x91, 0xe9, 0x79, 0x9e, 0xac, 0xff,
	0x6f, 0xd2, 0xe6, 0x99, 0x7d, 0xc9, 0x8d, 0xb9, 0x37, 0xf9, 0x77, 0xf5, 0x3f, 0xe0, 0xf5, 0x5c,
	0xfd, 0xb5, 0x08, 0xfc, 0xa1, 0xd0, 0xbe, 0x8c, 0x3a, 0x72, 0x88, 0x0f, 0x03, 0x7f, 0x80, 0x9a,
	0x8b, 0x23, 0x6f, 0xa0, 0x36, 0x76, 0x32, 0x86, 0x53, 0xe2, 0x4b, 0x59, 0x76, 0x35, 0xff, 0x66,
	0xcc, 0x05, 0xe3, 0x6d, 0x24, 0x50, 0xa8, 0xc4, 0x5a, 0x28, 0xed, 0x25, 0x61, 0x36, 0xc4, 0x59,
	0xcc, 0x4e, 0xa1, 0xd2, 0xd5, 0xa8, 0x84, 0x96, 0x8a, 0x1c, 0x03, 0xf8, 0xd9, 0x73, 0x46, 0x29,
	0xf1, 0x85, 0xcc, 0xd9, 0x9f, 0x32, 0xec, 0x66, 0xd6, 0xfa, 0x8a, 0xa8, 0xc8, 0x15, 0x3c, 0xce,
	0x99, 0x81, 0x34, 0x9a, 0xa9, 0x7f, 0x9b, 0xeb, 0x7c, 0x42, 0x0f, 0x1d, 0x8f, 0xcd, 0xca, 0xac,
	0x40, 0x3e, 0xc3, 0x93, 0x15, 0x2e, 0x21, 0xcc, 0x22, 0xd7, 0x5b, 0x88, 0xba, 0xc6, 0x65, 0x05,
	0xe2, 0x2d, 0x4d, 0xca, 0x3a, 0x83, 0xbc, 0x5a, 0x43, 0x73, 0x8c, 0x93, 0xe7, 0x75, 0xa0, 0xe6,
	0x7a, 0x82, 0x3c, 0x5f, 0x06, 0x39, 0x5e, 0xa1, 0x07, 0x96, 0xf0, 0x31, 0x1a, 0x63, 0x20, 0xef,
	0x90, 0x15, 0xc8, 0x4f, 0x78, 0xb6, 0xc1, 0x0f, 0xe4, 0x74, 0x15, 0x71, 0xb5, 0x69, 0x56, 0xe2,
	0xf3, 0xf3, 0x9b, 0x6e, 0xe9, 0xda, 0xf9, 0x2d, 0xac, 0x70, 0xfe, 0xbe, 0x3e, 0x1c, 0x6f, 0x5e,
	0x7e, 0xf2, 0x36, 0xaf, 0x76, 0x83, 0x49, 0xe8, 0xa1, 0x6d, 0x77, 0x9b, 0xdc, 0xd1, 0xa6, 0x4b,
	0x9d, 0x1f, 0xad, 0xb3, 0xec, 0xf4, 0xc0, 0x96, 0xed, 0xea, 0xb2, 0x02, 0x79, 0x07, 0x7b, 0x36,
	0xf2, 0x70, 0xa2, 0x49, 0xae, 0x27, 0x7f, 0xc5, 0x73, 0xd8, 0xb7, 0xc5, 0x4e, 0x20, 0x63, 0x5c,
	0xf1, 0x4e, 0x6d, 0x2e, 0xc4, 0xfc, 0xfe, 0x17, 0xfa, 0x65, 0xf3, 0x2f, 0x73, 0xfe, 0x37, 0x00,
	0x00, 0xff, 0xff, 0xe0, 0x19, 0x4c, 0xae, 0xc8, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StoragePeerClient is the client API for StoragePeer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StoragePeerClient interface {
	GetBlockchainInfo(ctx context.Context, in *GetBlockchainInfoRequest, opts ...grpc.CallOption) (*common.BlockchainInfo, error)
	RetrieveBlockByHash(ctx context.Context, in *RetrieveBlockByHashRequest, opts ...grpc.CallOption) (*common.Block, error)
	RetrieveBlockByNumber(ctx context.Context, in *RetrieveBlockByNumberRequest, opts ...grpc.CallOption) (*common.Block, error)
	RetrieveTxByID(ctx context.Context, in *RetrieveTxByIDRequest, opts ...grpc.CallOption) (*common.Envelope, error)
	RetrieveTxByBlockNumTranNum(ctx context.Context, in *RetrieveTxByBlockNumTranNumRequest, opts ...grpc.CallOption) (*common.Envelope, error)
	RetrieveBlockByTxID(ctx context.Context, in *RetrieveBlockByTxIDRequest, opts ...grpc.CallOption) (*common.Block, error)
	RetrieveTxValidationCodeByTxID(ctx context.Context, in *RetrieveTxValidationCodeByTxIDRequest, opts ...grpc.CallOption) (*ValidationCode, error)
	RetrieveBlocks(ctx context.Context, in *RetrieveBlocksRequest, opts ...grpc.CallOption) (*Iterator, error)
	IteratorNext(ctx context.Context, in *Iterator, opts ...grpc.CallOption) (*common.Block, error)
	IteratorClose(ctx context.Context, in *Iterator, opts ...grpc.CallOption) (*Result, error)
}

type storagePeerClient struct {
	cc *grpc.ClientConn
}

func NewStoragePeerClient(cc *grpc.ClientConn) StoragePeerClient {
	return &storagePeerClient{cc}
}

func (c *storagePeerClient) GetBlockchainInfo(ctx context.Context, in *GetBlockchainInfoRequest, opts ...grpc.CallOption) (*common.BlockchainInfo, error) {
	out := new(common.BlockchainInfo)
	err := c.cc.Invoke(ctx, "/remote.StoragePeer/GetBlockchainInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storagePeerClient) RetrieveBlockByHash(ctx context.Context, in *RetrieveBlockByHashRequest, opts ...grpc.CallOption) (*common.Block, error) {
	out := new(common.Block)
	err := c.cc.Invoke(ctx, "/remote.StoragePeer/RetrieveBlockByHash", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storagePeerClient) RetrieveBlockByNumber(ctx context.Context, in *RetrieveBlockByNumberRequest, opts ...grpc.CallOption) (*common.Block, error) {
	out := new(common.Block)
	err := c.cc.Invoke(ctx, "/remote.StoragePeer/RetrieveBlockByNumber", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storagePeerClient) RetrieveTxByID(ctx context.Context, in *RetrieveTxByIDRequest, opts ...grpc.CallOption) (*common.Envelope, error) {
	out := new(common.Envelope)
	err := c.cc.Invoke(ctx, "/remote.StoragePeer/RetrieveTxByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storagePeerClient) RetrieveTxByBlockNumTranNum(ctx context.Context, in *RetrieveTxByBlockNumTranNumRequest, opts ...grpc.CallOption) (*common.Envelope, error) {
	out := new(common.Envelope)
	err := c.cc.Invoke(ctx, "/remote.StoragePeer/RetrieveTxByBlockNumTranNum", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storagePeerClient) RetrieveBlockByTxID(ctx context.Context, in *RetrieveBlockByTxIDRequest, opts ...grpc.CallOption) (*common.Block, error) {
	out := new(common.Block)
	err := c.cc.Invoke(ctx, "/remote.StoragePeer/RetrieveBlockByTxID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storagePeerClient) RetrieveTxValidationCodeByTxID(ctx context.Context, in *RetrieveTxValidationCodeByTxIDRequest, opts ...grpc.CallOption) (*ValidationCode, error) {
	out := new(ValidationCode)
	err := c.cc.Invoke(ctx, "/remote.StoragePeer/RetrieveTxValidationCodeByTxID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storagePeerClient) RetrieveBlocks(ctx context.Context, in *RetrieveBlocksRequest, opts ...grpc.CallOption) (*Iterator, error) {
	out := new(Iterator)
	err := c.cc.Invoke(ctx, "/remote.StoragePeer/RetrieveBlocks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storagePeerClient) IteratorNext(ctx context.Context, in *Iterator, opts ...grpc.CallOption) (*common.Block, error) {
	out := new(common.Block)
	err := c.cc.Invoke(ctx, "/remote.StoragePeer/IteratorNext", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storagePeerClient) IteratorClose(ctx context.Context, in *Iterator, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/remote.StoragePeer/IteratorClose", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StoragePeerServer is the server API for StoragePeer service.
type StoragePeerServer interface {
	GetBlockchainInfo(context.Context, *GetBlockchainInfoRequest) (*common.BlockchainInfo, error)
	RetrieveBlockByHash(context.Context, *RetrieveBlockByHashRequest) (*common.Block, error)
	RetrieveBlockByNumber(context.Context, *RetrieveBlockByNumberRequest) (*common.Block, error)
	RetrieveTxByID(context.Context, *RetrieveTxByIDRequest) (*common.Envelope, error)
	RetrieveTxByBlockNumTranNum(context.Context, *RetrieveTxByBlockNumTranNumRequest) (*common.Envelope, error)
	RetrieveBlockByTxID(context.Context, *RetrieveBlockByTxIDRequest) (*common.Block, error)
	RetrieveTxValidationCodeByTxID(context.Context, *RetrieveTxValidationCodeByTxIDRequest) (*ValidationCode, error)
	RetrieveBlocks(context.Context, *RetrieveBlocksRequest) (*Iterator, error)
	IteratorNext(context.Context, *Iterator) (*common.Block, error)
	IteratorClose(context.Context, *Iterator) (*Result, error)
}

// UnimplementedStoragePeerServer can be embedded to have forward compatible implementations.
type UnimplementedStoragePeerServer struct {
}

func (*UnimplementedStoragePeerServer) GetBlockchainInfo(ctx context.Context, req *GetBlockchainInfoRequest) (*common.BlockchainInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlockchainInfo not implemented")
}
func (*UnimplementedStoragePeerServer) RetrieveBlockByHash(ctx context.Context, req *RetrieveBlockByHashRequest) (*common.Block, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetrieveBlockByHash not implemented")
}
func (*UnimplementedStoragePeerServer) RetrieveBlockByNumber(ctx context.Context, req *RetrieveBlockByNumberRequest) (*common.Block, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetrieveBlockByNumber not implemented")
}
func (*UnimplementedStoragePeerServer) RetrieveTxByID(ctx context.Context, req *RetrieveTxByIDRequest) (*common.Envelope, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetrieveTxByID not implemented")
}
func (*UnimplementedStoragePeerServer) RetrieveTxByBlockNumTranNum(ctx context.Context, req *RetrieveTxByBlockNumTranNumRequest) (*common.Envelope, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetrieveTxByBlockNumTranNum not implemented")
}
func (*UnimplementedStoragePeerServer) RetrieveBlockByTxID(ctx context.Context, req *RetrieveBlockByTxIDRequest) (*common.Block, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetrieveBlockByTxID not implemented")
}
func (*UnimplementedStoragePeerServer) RetrieveTxValidationCodeByTxID(ctx context.Context, req *RetrieveTxValidationCodeByTxIDRequest) (*ValidationCode, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetrieveTxValidationCodeByTxID not implemented")
}
func (*UnimplementedStoragePeerServer) RetrieveBlocks(ctx context.Context, req *RetrieveBlocksRequest) (*Iterator, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetrieveBlocks not implemented")
}
func (*UnimplementedStoragePeerServer) IteratorNext(ctx context.Context, req *Iterator) (*common.Block, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IteratorNext not implemented")
}
func (*UnimplementedStoragePeerServer) IteratorClose(ctx context.Context, req *Iterator) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IteratorClose not implemented")
}

func RegisterStoragePeerServer(s *grpc.Server, srv StoragePeerServer) {
	s.RegisterService(&_StoragePeer_serviceDesc, srv)
}

func _StoragePeer_GetBlockchainInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlockchainInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoragePeerServer).GetBlockchainInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/remote.StoragePeer/GetBlockchainInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoragePeerServer).GetBlockchainInfo(ctx, req.(*GetBlockchainInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoragePeer_RetrieveBlockByHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrieveBlockByHashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoragePeerServer).RetrieveBlockByHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/remote.StoragePeer/RetrieveBlockByHash",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoragePeerServer).RetrieveBlockByHash(ctx, req.(*RetrieveBlockByHashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoragePeer_RetrieveBlockByNumber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrieveBlockByNumberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoragePeerServer).RetrieveBlockByNumber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/remote.StoragePeer/RetrieveBlockByNumber",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoragePeerServer).RetrieveBlockByNumber(ctx, req.(*RetrieveBlockByNumberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoragePeer_RetrieveTxByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrieveTxByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoragePeerServer).RetrieveTxByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/remote.StoragePeer/RetrieveTxByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoragePeerServer).RetrieveTxByID(ctx, req.(*RetrieveTxByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoragePeer_RetrieveTxByBlockNumTranNum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrieveTxByBlockNumTranNumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoragePeerServer).RetrieveTxByBlockNumTranNum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/remote.StoragePeer/RetrieveTxByBlockNumTranNum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoragePeerServer).RetrieveTxByBlockNumTranNum(ctx, req.(*RetrieveTxByBlockNumTranNumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoragePeer_RetrieveBlockByTxID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrieveBlockByTxIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoragePeerServer).RetrieveBlockByTxID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/remote.StoragePeer/RetrieveBlockByTxID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoragePeerServer).RetrieveBlockByTxID(ctx, req.(*RetrieveBlockByTxIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoragePeer_RetrieveTxValidationCodeByTxID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrieveTxValidationCodeByTxIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoragePeerServer).RetrieveTxValidationCodeByTxID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/remote.StoragePeer/RetrieveTxValidationCodeByTxID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoragePeerServer).RetrieveTxValidationCodeByTxID(ctx, req.(*RetrieveTxValidationCodeByTxIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoragePeer_RetrieveBlocks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrieveBlocksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoragePeerServer).RetrieveBlocks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/remote.StoragePeer/RetrieveBlocks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoragePeerServer).RetrieveBlocks(ctx, req.(*RetrieveBlocksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoragePeer_IteratorNext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Iterator)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoragePeerServer).IteratorNext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/remote.StoragePeer/IteratorNext",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoragePeerServer).IteratorNext(ctx, req.(*Iterator))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoragePeer_IteratorClose_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Iterator)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoragePeerServer).IteratorClose(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/remote.StoragePeer/IteratorClose",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoragePeerServer).IteratorClose(ctx, req.(*Iterator))
	}
	return interceptor(ctx, in, info, handler)
}

var _StoragePeer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "remote.StoragePeer",
	HandlerType: (*StoragePeerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBlockchainInfo",
			Handler:    _StoragePeer_GetBlockchainInfo_Handler,
		},
		{
			MethodName: "RetrieveBlockByHash",
			Handler:    _StoragePeer_RetrieveBlockByHash_Handler,
		},
		{
			MethodName: "RetrieveBlockByNumber",
			Handler:    _StoragePeer_RetrieveBlockByNumber_Handler,
		},
		{
			MethodName: "RetrieveTxByID",
			Handler:    _StoragePeer_RetrieveTxByID_Handler,
		},
		{
			MethodName: "RetrieveTxByBlockNumTranNum",
			Handler:    _StoragePeer_RetrieveTxByBlockNumTranNum_Handler,
		},
		{
			MethodName: "RetrieveBlockByTxID",
			Handler:    _StoragePeer_RetrieveBlockByTxID_Handler,
		},
		{
			MethodName: "RetrieveTxValidationCodeByTxID",
			Handler:    _StoragePeer_RetrieveTxValidationCodeByTxID_Handler,
		},
		{
			MethodName: "RetrieveBlocks",
			Handler:    _StoragePeer_RetrieveBlocks_Handler,
		},
		{
			MethodName: "IteratorNext",
			Handler:    _StoragePeer_IteratorNext_Handler,
		},
		{
			MethodName: "IteratorClose",
			Handler:    _StoragePeer_IteratorClose_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fastfabric/remote/storage.proto",
}
