version: '3.1'

services:

  mongo:
    image: mongo:3
    restart: always
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
      - "27018:28018"
    environment:
      - NO_USED=0
    volumes:
      - /opt/cello/mongo:/data/db

