---
- hosts: cdt
  remote_user: root
  vars:
    destdir: /root/ansible
    # srcdir: ../../dist
  tasks:

  # - name: Copy docker config to {{destdir}}
  #   copy: src={{srcdir}}/docker-compose-{{ip}}.yaml dest={{destdir}}/docker-compose.yaml
  #         force=true

  - name: down
    shell: source /root/miniconda3/bin/activate caliper && docker-compose -f {{destdir}}/docker-compose.yaml down 
    args:
      executable: /bin/bash
    ignore_errors: True

  # - name: down
  #   shell: docker-compose -f {{destdir}}/docker-compose.yaml down 
  #   args:
  #     executable: /bin/bash
    # ignore_errors: True

  - name: rmimages
    shell: docker rm $(docker ps -aq) && docker rmi $(docker images | grep dev | awk '{print $3 }')
    args:
      executable: /bin/bash
    ignore_errors: True



