# input: 
# arg1: orderer_count=3  
# arg2: peerorgs=[{ orgname: "org1.example.com", count:10 }]


OrdererOrgs:
- Name: Orderer
  Domain: example.com

  Template:
      Count: 3

PeerOrgs:
  
- Name: Org1
  Domain: org1.example.com
  Template:
      Count: 2
  Users:
      Count: 1
  
- Name: Org2
  Domain: org2.example.com
  Template:
      Count: 2
  Users:
      Count: 1
