# args:  
# param1:   orgs=[ {"org":"org1", "anchorpeer": {"name": "peer0.org1.example.com", "port": 7051}]
# param2:   orderes=[{"name":"ordere0.example.com", "port":7050}]
# param3:   action

---

Organizations:
- &OrdererOrg
    Name: OrdererMSP
    ID: OrdererMSP
    MSPDir: crypto-config/ordererOrganizations/example.com/msp
    AdminPrincipal: Role.MEMBER
{% for item in orgs %}
- &{{item["org"].capitalize()}}
    Name: {{item["org"].capitalize()}}MSP
    ID: {{item["org"].capitalize()}}MSP
    MSPDir: crypto-config/peerOrganizations/{{item["org"]}}.example.com/msp
    AdminPrincipal: Role.ADMIN
    AnchorPeers:
    - Host: {{item["anchorpeer"]["name"]}}
      Port: {{item["anchorpeer"]["port"]}}
{% endfor %}

Orderer: &OrdererDefaults
    OrdererType: etcdraft
    Addresses:
    {% for orderer in orderers %}
    - {{orderer.name}}:{{orderer.port}}
    {% endfor %}

    BatchTimeout: {{action['BatchTimeout']}}
    BatchSize:
        MaxMessageCount: {{action['MaxMessageCount']}}
        AbsoluteMaxBytes: {{action['AbsoluteMaxBytes']}}
        PreferredMaxBytes: {{action['PreferredMaxBytes']}}

    MaxChannels: 0
    EtcdRaft:
        Consenters:
        {% for orderer in orderers %}
        - Host: {{orderer.name}}
          Port: {{orderer.port}}
          ClientTLSCert: crypto-config/ordererOrganizations/example.com/orderers/{{orderer.name}}/tls/server.crt
          ServerTLSCert: crypto-config/ordererOrganizations/example.com/orderers/{{orderer.name}}/tls/server.crt
        {% endfor %}

        Options:
            # ElectionTick: {{action['ElectionTick']}}
            # HeartbeatTick: {{action['HeartbeatTick']}}
            # MaxInflightBlocks: {{action['MaxInflightBlocks']}}
            # SnapshotIntervalSize: {{action['SnapshotIntervalSize']}}
            # TickInterval: {{action['TickInterval']}}
            ElectionTick: 10
            HeartbeatTick: 1
            MaxInflightBlocks: 5
            SnapshotIntervalSize: 20 MB
            TickInterval: 500ms

    Organizations:

Application: &ApplicationDefaults
    Organizations:

Profiles:
    OrdererGenesis:
        Orderer:
            <<: *OrdererDefaults
            Organizations:
            - *OrdererOrg
        Consortiums:
            SampleConsortium:
                Organizations:
                {% for item in orgs %}
                - *{{item["org"].capitalize()}}
                {% endfor %}
    ChannelConfig:
        Consortium: SampleConsortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
            {% for item in orgs %}
            - *{{item["org"].capitalize()}}
            {% endfor %}
