# input: 
# arg1: orderer_count=3  
# arg2: peerorgs=[{ orgname: "org1.example.com", count:10 }]


OrdererOrgs:
- Name: Orderer
  Domain: example.com

  Template:
      Count: {{orderer_count}}

PeerOrgs:
{% for item in peerorgs %}  
- Name: {{item.orgname.capitalize().split(".")[0]}}
  Domain: {{item.orgname}}
  Template:
      Count: {{item.count}}
  Users:
      Count: 1
{% endfor %}
