---
test:
  name: clinic
  description: This is an example benchmark for caliper, to test the backend DLT's
    performance with simple account opening & querying transactions
  workers:
    type: local
    number: 1
  rounds:
  - label: open
    description: Test description for the opening of an account through the deployed chaincode
    txNumber: 100
    rateControl:
      type: fixed-rate
      opts:
        tps: 50
    arguments:
      txnPerBatch: 1
    callback: benchmarks/scenario/company/open.js
monitor:
  type:
  - docker
  docker:
    name:
    - all
  interval: 1
